export type SlopSignal = {
  id: string;
  label: string;
  weight: number;
  count: number;
  files: string[];
};

export type SlopResult = {
  overallPercent: number;
  humanReviewConfidence: number;
  topCauses: SlopSignal[];
  affectedFiles: string[];
  recommendedFixes: string[];
  signals: SlopSignal[];
};

export type SlopScanInput = {
  files: Array<{ path: string; content: string; lines: number }>;
};

const GENERIC_NAMES = [
  "handleData",
  "processData",
  "helper",
  "utils",
  "manager",
  "wrapper",
  "doSomething",
];

const PROMPT_COMMENTS = [
  "todo: implement",
  "add logic here",
  "placeholder",
  "generated by",
  "fixme",
  "as an ai",
];

export function scanAiSlop(input: SlopScanInput): SlopResult {
  const signals: SlopSignal[] = [
    { id: "bloated", label: "Bloated files (>400 lines)", weight: 1.2, count: 0, files: [] },
    { id: "todos", label: "Excessive TODO/FIXME comments", weight: 1.0, count: 0, files: [] },
    { id: "generic", label: "Generic function/type names", weight: 0.9, count: 0, files: [] },
    { id: "prompt", label: "Prompt-like comments", weight: 1.1, count: 0, files: [] },
    { id: "empty-catch", label: "Empty catch blocks", weight: 1.3, count: 0, files: [] },
    { id: "duplicate", label: "Duplicated helper patterns", weight: 1.0, count: 0, files: [] },
    { id: "console", label: "Debug console logging left in", weight: 0.6, count: 0, files: [] },
  ];

  const helperNames = new Map<string, number>();

  for (const file of input.files) {
    const lower = file.content.toLowerCase();
    const path = file.path;

    if (file.lines > 400) {
      bump(signals, "bloated", path);
    }

    const todoCount = (file.content.match(/\b(TODO|FIXME|HACK)\b/g) ?? []).length;
    if (todoCount >= 4) {
      signals.find((s) => s.id === "todos")!.count += todoCount;
      signals.find((s) => s.id === "todos")!.files.push(path);
    }

    for (const name of GENERIC_NAMES) {
      if (lower.includes(name.toLowerCase())) {
        bump(signals, "generic", path);
        helperNames.set(name, (helperNames.get(name) ?? 0) + 1);
      }
    }

    for (const phrase of PROMPT_COMMENTS) {
      if (lower.includes(phrase)) bump(signals, "prompt", path);
    }

    if (/catch\s*\([^)]*\)\s*\{\s*\}/.test(file.content)) {
      bump(signals, "empty-catch", path);
    }

    if ((file.content.match(/console\.(log|debug)\(/g) ?? []).length >= 3) {
      bump(signals, "empty-catch", path);
      signals.find((s) => s.id === "console")!.count += 1;
      if (!signals.find((s) => s.id === "console")!.files.includes(path)) {
        signals.find((s) => s.id === "console")!.files.push(path);
      }
    }
  }

  for (const [, count] of helperNames) {
    if (count >= 3) {
      const sig = signals.find((s) => s.id === "duplicate")!;
      sig.count += count;
    }
  }

  const weighted = signals.reduce((sum, s) => sum + s.count * s.weight, 0);
  const fileCount = Math.max(1, input.files.length);
  const overallPercent = Math.min(100, Math.round((weighted / fileCount) * 8));

  const topCauses = [...signals]
    .filter((s) => s.count > 0)
    .sort((a, b) => b.count * b.weight - a.count * a.weight)
    .slice(0, 5);

  const affectedFiles = [...new Set(signals.flatMap((s) => s.files))].slice(0, 20);

  const recommendedFixes = topCauses.map((c) => fixForSignal(c.id));

  const humanReviewConfidence = Math.max(
    40,
    Math.min(98, 90 - overallPercent * 0.4 + topCauses.length * 2),
  );

  return {
    overallPercent,
    humanReviewConfidence: Math.round(humanReviewConfidence),
    topCauses,
    affectedFiles,
    recommendedFixes,
    signals,
  };
}

function bump(signals: SlopSignal[], id: string, path: string) {
  const sig = signals.find((s) => s.id === id);
  if (!sig) return;
  sig.count += 1;
  if (!sig.files.includes(path)) sig.files.push(path);
}

function fixForSignal(id: string): string {
  switch (id) {
    case "bloated":
      return "Split large files into focused modules with single responsibilities.";
    case "todos":
      return "Resolve or ticket TODOs; remove stale placeholder comments.";
    case "generic":
      return "Rename generic helpers to domain-specific names that explain intent.";
    case "prompt":
      return "Replace placeholder comments with real documentation or delete them.";
    case "empty-catch":
      return "Handle errors explicitly or rethrow with context — never swallow silently.";
    case "duplicate":
      return "Consolidate duplicated helpers into one shared utility.";
    case "console":
      return "Remove debug logging or route through a proper logger.";
    default:
      return "Review flagged files manually and refactor for clarity.";
  }
}
